name: C/C++ CI

on:
  push:
    branches: [ 1stNUP-Installer ]
  pull_request:
    branches: [ 1stNUP-Installer ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run : |
        docker pull devkitpro/devkitppc
        docker build -t builder .
        docker run --name build builder /bin/bash -c make
        docker cp build:/Hinata-Installer/indexiine-installer.elf 1stNUP-installer.elf
        docker rm build && docker image rm builder
    - uses: actions/upload-artifact@v2.2.4
      with:
        name: Binaries
        path: ${{ github.workspace }}/*.elf