name: C/C++ CI

on:
  push:
    branches: [ Rosalina-Theme-Installer ]
  pull_request:
    branches: [ Rosalina-Theme-Installer ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2.2.2
    - run : |
        docker pull devkitpro/devkitppc
        docker build -t builder .
        docker run --name build builder /bin/bash -c make
        docker cp build:/Hinata-Installer/indexiine-installer.elf rosalina-theme-installer-men2.elf
        docker rm build && docker image rm builder
        python ToMen.py
        docker build -t builder .
        docker run --name build builder /bin/bash -c make
        docker cp build:/Hinata-Installer/indexiine-installer.elf rosalina-theme-installer-men.elf
        docker rm build && docker image rm builder
    - uses: actions/upload-artifact@v2.2.4
      with:
        name: Binaries
        path: ${{ github.workspace }}/*.elf
